### ISSUE TITLE
Yew trees behind varrock palace not counting

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [Infinitay/tree-count-plugin#29]
The yew trees behind the varrock palace are not being tracked by the addon, verified the addon was working elsewhere though.

**Comment by Infinitay** [comment]
Sorry for the issue. I noticed this the other day when fixing the other issues with the logic. The reason the trees behind Varrock aren't being tracked is because the tree's ID differs than the ids I had previously of yew trees. Although you just made me realize that I forgot to push the changes. I had it changed locally but at some point I must have undid it when separating my changes.

I'll go ahead and fix this right away. Thanks for bringing it up again otherwise I would have missed it in the existing update that is pending (https://github.com/runelite/plugin-hub/pull/5224)

**Comment by Jin-Jiyunsun** [comment]
thanks!

**Comment by Infinitay** [comment]
RuneLite approved and pushed the update to the plugin hub. I'll go ahead and close this now. Thanks again for reporting it and waiting.
